server:
  port: 8888

#mysql
#spring:
#  datasource:
#    url: jdbc:mysql://192.168.48.128:3306/test?characterEncoding=UTF-8
#    driver-class-name: com.mysql.jdbc.Driver
#    username: root
#    password: root


#sqlserver
spring:
  datasource:
    url: jdbc:sqlserver://desktop-32113r4:1433;databaseName=FPSO
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    password: root


mybatis:
  mapper-locations: classpath:mapper/*.xml


#open chrome after start up
start:
  auto: false
  chromeAddr: C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
  url: http://localhost:8888/mybatis/findAll
